services:
  db:
    platform: linux/amd64
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: "femr_db"
      MYSQL_USER: "femr"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    command:
      - "--log-bin-trust-function-creators=1"
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql

  femr:
    platform: linux/amd64
    image: teamfemrdev/teamfemr:latest
    links:
      - db:mysql
    depends_on:
      db:
        condition: service_healthy
    tty: true
    restart: on-failure:10
    ports:
      - "9000:9000"
    expose:
      - "9000"
    environment:
      DB_URL: 'jdbc:mysql://db:3306/femr_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true'
      DB_USER: 'femr'
      DB_PASS: 'password'
      IS_DOCKER: 'true'
    volumes:
      - ./femr/conf:/home/femrapp/conf


volumes:
  db-data: