name: Push Installer to s3

on:
  push:
    branches:
      - karan_installer # Placeholder for now, should activate on release in femr repo

jobs:
  release:
    name: Run release.py
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: python release.py --version 3.0.0 #placeholder for now, should be updated to get version from femr repo

